// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project1;

{ITE} {DFMFileType} {pocetna.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {DFMFileType} {Unit3.dfm}
{ITE} {DFMFileType} {Unit4.dfm}
{ITE} {DFMFileType} {Unit5.dfm}
{ITE} {RCFileType} {Project1_DRC.rc}

{$R 'pocetna.dfm' 'Form1:TForm'}
{$R 'Unit2.dfm' 'Form2:TForm'}
{$R 'Unit3.dfm' 'Form3:TForm'}
{$R 'Unit4.dfm' 'Form4:TForm'}
{$R 'Unit5.dfm' 'Form5:TForm'}
{$R 'Project1_DRC.res' 'Project1_DRC.rc'}

{$E HRV}

begin
end.
